Project1
Mswork6/java-course-2023 pull request #3
Opened 2023-10-22 19:50 UTC by Mswork6

2023-11-05 10:37 UTC, Mswork6 commented
Я немного набалбесил и создал ветку проекта не от мастера, а от второй домашки и поэтому сюда немного лишнего попало видимо :-(
К проекту относятся только файлы ConsoleHangman, Dictionary, GameDictionary, GuessResult, Main, Session, UnsupportedOperationException.

2023-11-06 18:39 UTC, dmskorikov requested changes

2023-11-06 18:39 UTC, dmskorikov commented on src/main/java/edu/project1/GameDictionary.java
> +        String[] words = {"баг", "фича", "джун", "уронил", "прод", "мидл", "сеньор", "джава"};
:minor: Если смотреть на задачу как на написание некоей системы, то хотелось бы иметь возможность задавать слова для игры "снаружи" из клиентского кода. Т.е. сделать возможность иметь не фикс.набор слов, а динамически создавать этот набор до начала игры.

2023-11-06 18:39 UTC, dmskorikov commented on src/main/java/edu/project1/ConsoleHangman.java
> +        this.session = new Session(answer, MAX_ATTEMPTS);
:minor: Непонятно зачем нужен еще один конструктор, если можно передать в первый конструктор словарь с одним нужным словом. К вопросу о возможности задания словаря в клиентском коде

2023-11-06 18:39 UTC, dmskorikov commented on src/main/java/edu/project1/ConsoleHangman.java
> +        System.out.println(message);
:major: Не очень удачное название метода - тут же не вывод в лог, а вывод какой-то строки для пользователя в процессе игры. Нужно переименовать во что-то более подходящее

2023-11-06 18:39 UTC, dmskorikov commented on src/main/java/edu/project1/ConsoleHangman.java
> +        Scanner scanner = new Scanner(System.in);
:minor: Можно не привязываться к вводу с консоли, тогда в тестах можно тестировать и этот метод

2023-11-06 18:39 UTC, dmskorikov commented on src/main/java/edu/project1/ConsoleHangman.java
> +    public GuessResult handleCommand(String command) throws UnsupportedOperationException {
:major: Метод, который имеет побочные эффекты в виде изменения переменной класса. Очень сложно потом читать и поддерживать такой код. Лучше менять поля класса в основной логике. В данном случае метод вообще не нужен, так как выше писал, что результат нужно перенести в сессию, которую сделать локальной переменной метода run

2023-11-06 18:39 UTC, dmskorikov commented on src/main/java/edu/project1/ConsoleHangman.java
> +        if (command.length() != 1) {
:major: проверку на невалидный ввод нужно делать первой, а уже после нее можно делать какие-то действия с валидным вводом. Нужно поднять наверх метода

2023-11-06 18:39 UTC, dmskorikov commented on src/main/java/edu/project1/ConsoleHangman.java
> +    private GuessResult result;
:major: Нарушение принципа SRP, логично хранить result внутри игровой сессии. Нужно перенести внутрь session

2023-11-06 18:39 UTC, dmskorikov commented on src/main/java/edu/project1/ConsoleHangman.java
> +    private final Session session;
:major: приватные поля класса нужны для хранения состояния между вызовами методов класса. У тебя же вся работа с сессией идет внутри метода run(). Поэтому session нужно сделать локальной переменной метода run()

2023-11-06 18:39 UTC, dmskorikov commented on src/main/java/edu/project1/ConsoleHangman.java
> +        return session.guess(guess);
:major: Тоже непонятно зачем сделан отдельный метод, а не вызывается session.guess по месту. Нужно удалить метод

2023-11-06 18:39 UTC, dmskorikov commented on src/main/java/edu/project1/GuessResult.java
> +    char[] state();
:major: Видимо предполагалось, что текущее состояние игры будет записываться в это поле. Но у тебя текущее состояние записывается вместе с message для SuccessfulGuess и FailedGuess
Нужно либо переписать и передавать состояние через это поле, либо вообще его удалить. Но правильнее оставить и переписать логику, чтобы это поле использовалось. А в SuccessfulGuess и в FailedGuess в поле message не писалось состояние. Тогда проще будет писать тесты

2023-11-06 18:39 UTC, dmskorikov commented on src/main/java/edu/project1/GuessResult.java
> +    int maxAttempts();
:major: Это поле из примера, но оно никак не используется поэтому его нужно удалить, включая реализацию в потомках. Либо начать как-то использовать

2023-11-06 18:39 UTC, dmskorikov commented on src/main/java/edu/project1/Session.java
> +        this.attempts = maxAttempts;
:major: у тебя тут хранится оставшееся количество попыток, а не количество использованных попыток. В этом случае непонятно зачем хранить maxAttempts. Нужно либо удалить поле maxAttempts, либо изменить логику и хранить количество использованных попыток

2023-11-06 18:39 UTC, dmskorikov commented on src/main/java/edu/project1/Session.java
> +        } else if (found) {
:minor: можно не писать else, если перед этим в ветке сделан return

2023-11-06 18:39 UTC, dmskorikov commented on src/main/java/edu/project1/Session.java
> +            if (answer.charAt(i) == guess && userAnswer[i] == '*') {
:major: не рассмотрен случай, если пользователь по ошибке ввел ранее введенную правильную букву. Я бы предложил считать это повторным правильным ответом.

2023-11-06 18:39 UTC, dmskorikov commented on src/main/java/edu/project1/ConsoleHangman.java
> +    private static final int MAX_ATTEMPTS = 10;
:major: Нужно сделать максимальное количество попыток полем класса, которое задается через конструктор. Так будет удобнее писать тесты

2023-11-06 18:39 UTC, dmskorikov commented on src/test/java/edu/project1/Project1Test.java
> +        hangman.handleCommand("z");
:minor: Можно же через цикл сделать?

2023-11-06 18:39 UTC, dmskorikov commented on src/test/java/edu/project1/Project1Test.java
> +        var resultNotGuessed = hangman.handleCommand("ж");
:major: названия полей не соответствуют содержанию. Тут должно быть resultGuessed,  ниже resultNotGuessed

2023-11-06 18:39 UTC, dmskorikov commented on src/test/java/edu/project1/Project1Test.java
> +public class Project1Test {
:major: Нет тестов на session и логику guess(). Надо дописать

2023-11-19 08:35 UTC, dmskorikov approved these changes

2023-11-19 08:35 UTC, dmskorikov commented on src/main/java/edu/project1/ConsoleHangman.java
> +    /* Конструктор больше для отладки, чтобы можно было отслеживать изменения в сессии.
я бы все же оставил только один конструктор с dictionary и maxAttempts, потому что второй у тебя используется только для тестирования. А это не очень хорошо выставлять какие-то внутренности реализации для возможности тестирования. 
Ну и этот конструктор используется только для checkGuessingWord() и checkIncorrectInput(), хотя их можно переписать без использования этого конструктора

2023-11-19 08:35 UTC, dmskorikov commented on src/main/java/edu/project1/ConsoleHangman.java
> +    private record GameInformer(PrintStream output) {
Тут необязательно было использовать record, так как он предназначен для хранения и передачи каких-то данных как внутри, так и снаружи приложения. Достаточно было просто класса

2023-11-19 08:35 UTC, dmskorikov commented on src/main/java/edu/project1/ConsoleHangman.java
> +                    processCommand(token);
Можно было сразу в processCommand() в конце вызывать session.getResult() и возвращать этот результат

2023-11-20 17:31 UTC, merged